services:
  - type: web
    name: medassist-backend
    env: docker
    buildCommand: docker build -t medassist-backend .
    startCommand: docker run -p 8000:8000 medassist-backend
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: containers-us-west-198.railway.app
      - key: DB_PORT
        value: 7317
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: guXHsVdoEcnAYrCyUlLGaXMFFkOtRuFi